/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Connexion;
import models.LocalConfig;
import models.User;
import models.Utils;

/**
 *
 * @author aicha
 */
public class ProfilView extends javax.swing.JFrame {

    private final LocalConfig config;
    private Connexion connect;
    private boolean edit = false;

    public ProfilView(Connexion connect) throws IOException, ClassNotFoundException, SQLException {
        config = LocalConfig.getConfig();
        this.connect = connect;
        if (this.connect == null) {
            this.connect = Connexion.makeConnexion();
        }

        initComponents();
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edit_profil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prenom_input = new javax.swing.JTextField();
        mail_input = new javax.swing.JTextField();
        color_input = new javax.swing.JColorChooser();
        nom_input = new javax.swing.JTextField();
        code_input = new javax.swing.JPasswordField();
        confirm_input = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edit_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        edit_profil.setText("Modifier");
        edit_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profilActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel8.setText("Prenom");

        jLabel9.setText("Email");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_mini.png"))); // NOI18N
        jLabel10.setText("Mot de passe");
        jLabel10.setToolTipText("8 charactère minimun avec au moin une majuscule et un chiffre");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel10.setIconTextGap(10);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel11.setText("Confirmation");

        jLabel12.setText("Couleur");

        prenom_input.setEditable(edit);
        prenom_input.setText(this.config.user.getPrenom());

        mail_input.setEditable(edit);
        mail_input.setText(this.config.user.getMail());

        color_input.setColor(this.config.usercolors.get(this.config.user.getId()));
        color_input.setEnabled(edit);

        nom_input.setEditable(edit);
        nom_input.setText(this.config.user.getNom());

        code_input.setEditable(edit);
        code_input.setText(this.config.user.getCode());

        confirm_input.setEditable(edit);
        confirm_input.setText(this.config.user.getCode());

        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Le mot de passe n'est pas sécurisé");
        jLabel2.setPreferredSize(new java.awt.Dimension(87, 28));

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Les mots de passe ne sont pas identiques");
        jLabel3.setPreferredSize(new java.awt.Dimension(87, 28));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(color_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(confirm_input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(code_input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(prenom_input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom_input, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prenom_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mail_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(code_input)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(confirm_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(color_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit_profil))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(edit_profil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lister.png"))); // NOI18N
        jMenuItem1.setText("Liste des projets");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jMenuItem2.setText("Déconnexion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2logoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2logoutActionPerformed
        try {
            LocalConfig conf = LocalConfig.getConfig();
            conf.user.reset();
            conf.saveConfig();
            new ConnexionView(connect).setVisible(true);
            this.dispose();
        }
        catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ProjectsListView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2logoutActionPerformed

    private void edit_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profilActionPerformed
        if (edit)
            save();
        
        edit = !edit;
        edition();
    }//GEN-LAST:event_edit_profilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            new ProjectsListView(connect).setVisible(true);
            this.dispose();
        }
        catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ProfilView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void save() {
        System.out.println("saving user");
        String nom_u = nom_input.getText(), prenom_u = prenom_input.getText(), 
        mail_u = mail_input.getText(), code_u = new String(code_input.getPassword()),
        conf_u = new String(confirm_input.getPassword());
        String color_u = Integer.toHexString(color_input.getColor().getRGB());
        color_u = "#" + color_u.substring(2, color_u.length());
        
        if(Utils.isNotEmpty(nom_u,prenom_u,mail_u,code_u,conf_u) && (conf_u.equals(code_u))){
            try {
                config.user.setCode(code_u);
                config.user.setNom(nom_u);
                config.user.setPrenom(prenom_u);
                config.user.setMail(mail_u);
                config.user.setCouleur(color_u);
                config.user.save(connect);
                
                HashMap<Integer,User> liste = User.getAllUsers(connect);
                for(int i : liste.keySet()){
                    User u_ = liste.get(i);
                    config.usernames.put(i, u_.getPrenom());
                    config.userview.put(i, true);
                    config.usercolors.put(i,Color.decode(u_.getCouleur()));
                }
                config.saveConfig();
            }
            catch (ClassNotFoundException | IOException | SQLException | IllegalArgumentException | IllegalAccessException ex) {
                Logger.getLogger(ProfilView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            reset();
        }
        
        /*
        if(u.connecter(connect)){
                HashMap<Integer,User> liste = User.getAllUsers(connect);
                LocalConfig conf = LocalConfig.getConfig();
                conf.user = u;
                for(int i : liste.keySet()){
                    User u_ = liste.get(i);
                    conf.usernames.put(i, u_.getPrenom());
                    conf.userview.put(i, true);
                    conf.usercolors.put(i,Color.decode(u_.getCouleur()));
                }
                conf.saveConfig();
                this.dispose();
                new ProjectsListView(connect).setVisible(true);
            }
            else{
                jLabel4.setVisible(true);
            }
        */
    }

    private void edition() {
        if (edit) {
            edit_profil.setText("Valider");
        }
        else {
            edit_profil.setText("Modifier");
        }

        nom_input.setEditable(edit);
        prenom_input.setEditable(edit);
        mail_input.setEditable(edit);
        code_input.setEditable(edit);
        confirm_input.setEditable(edit);
        color_input.setEnabled(edit);
    }

    private void reset() {
        nom_input.setText(config.user.getNom());
        prenom_input.setText(config.user.getPrenom());
        mail_input.setText(config.user.getMail());
        code_input.setText(config.user.getCode());
        confirm_input.setText(config.user.getCode());
        color_input.setColor(config.usercolors.get(config.user.getId()));
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField code_input;
    private javax.swing.JColorChooser color_input;
    private javax.swing.JPasswordField confirm_input;
    private javax.swing.JButton edit_profil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail_input;
    private javax.swing.JTextField nom_input;
    private javax.swing.JTextField prenom_input;
    // End of variables declaration//GEN-END:variables
}
