CREATE DATABASE IF NOT EXISTS planning;
USE planning;

CREATE TABLE IF NOT EXISTS taches(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
projet INT NOT NULL ,
user INT NOT NULL ,
creation BIGINT(14) NOT NULL ,
duree INT(8) NOT NULL ,
description TEXT NOT NULL ,
commentaires TEXT NOT NULL ,
v_user TINYINT(1) NOT NULL ,
v_admin TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
nom VARCHAR(128) NOT NULL ,
prenom VARCHAR(128) NOT NULL ,
email VARCHAR(128) NOT NULL ,
code VARCHAR(128) NOT NULL ,
couleur VARCHAR(128) NOT NULL ,
status INT NOT NULL
);

CREATE TABLE IF NOT EXISTS projets(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
titre VARCHAR(128) NOT NULL ,
description TEXT NOT NULL ,
duree_estimee INT NOT NULL ,
duree_reel INT NOT NULL ,
debut INT NOT NULL ,
fin INT NOT NULL,
creation INT NOT NULL
);
